#!/usr/bin/env bash

APP="stats" # name of your release

BUILD_HOST="tofu.wtf" # host where to build the release
BUILD_USER="elixir-prod" # local user at build host
BUILD_AT="/home/elixir-prod/stats/builds" # build directory on build host

#STAGING_HOSTS="test1.acme.org test2.acme.org" # staging / test hosts separated by space
#STAGING_USER="test" # local user at staging hosts
#TEST_AT="/test/my-erlang-app" # deploy directory on staging hosts. default is DELIVER_TO

#PRODUCTION_HOSTS="tofu.wtf" # deploy / production hosts separated by space
#PRODUCTION_USER="elixir-prod" # local user at deploy hosts
DELIVER_TO="/home/elixir-prod/stats/deploy" # deploy directory on production hosts

# For *Phoenix* projects, symlink prod.secret.exs to our tmp source
pre_erlang_get_and_update_deps() {
  local _prod_secret_path="/home/elixir-prod/stats/secret/prod.secret.exs"
  if [ "$TARGET_MIX_ENV" = "prod" ]; then
    __sync_remote "
      ln -sfn '$_prod_secret_path' '$BUILD_AT/config/prod.secret.exs'
    "
  fi
}